[package]
name = "echidna"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
compiler_builtins = { version = "0.1.87", features = ["mem"] }

[profile.dev]
overflow-checks = false
debug-assertions = false
lto = true
incremental = false
panic = "abort"
