[package]
name = "delf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99"
derive-try-from-primitive = "1.0.0"
nom = "7"
enumflags2 = "0.7"
thiserror = "1"
